Expose the external temperature and humidity overrides
LavermanJJ/home-assistant-solarfocus pull request #116
Opened 2024-12-29 13:20 UTC by lu-zero

Should make easier to deal with #108.

2025-01-03 13:00 UTC, LavermanJJ requested changes
Hi - thanks for taking your time and providing the PR 👍 Please see my comments.

2025-01-03 23:15 UTC, lu-zero commented on custom_components/solarfocus/number.py
> +        key="indoor_temperatur_external",
it is already present. 

```
4c628dad (laverman 2023-08-26 16:49:32 +0200 22)         self.indoor_temperatur_external = DataValue(address=6, multiplier=10, register_type=RegisterTypes.HOLDING)
4c628dad (laverman 2023-08-26 16:49:32 +0200 23)         self.indoor_humidity_external = DataValue(address=7, register_type=RegisterTypes.HOLDING)
```

2025-01-05 11:06 UTC, lu-zero commented
Or do you plan to land the renames in pysolarfocus so this should use the other names?

2025-01-05 13:25 UTC, LavermanJJ commented
No renaming planned. LGTM! Thanks for your contribution!

2025-01-05 13:26 UTC, LavermanJJ approved these changes

2025-01-05 13:27 UTC, merged